### PR TITLE
feat(nexus3): Updated image to v3.72.0

### PR DESCRIPTION
**Pull request by stevehipwell**
Outstanding work:

- [x] Test K8s resource migration from v4
- [x] Test Nexus3 migration
- [x] Separate config into `Job`
- [x] Update CHANGELOG & annotations

Closes #852
Closes #1003
Closes #1040

### CODE REVIEW

**Comment by stevehipwell** [comment]
CC @EugenMayer

**Comment by EugenMayer** [comment]
the removal of deployment just wiped my entire data since the pv/pvc was recreated on demand.

I hope you had that one on your radar when you decided to remove it

**Comment by stevehipwell** [comment]
@EugenMayer the deployment functionality has been marked as deprecated for a long time. This release was SemVer major and involved manual intervention, so it was the perfect time to remove the deployment pattern. I did cover this in the CHANGELOG, and it should have been clear in any diff.

I assume you have a backup? Do you want guidance on how to migrate to the StatefulSet pattern?

**Comment by stevehipwell** [comment]
@EugenMayer well I'm sorry it caught you out. I'd assumed that everyone using the chart for real had either migrated off the deployment pattern or was intending to on the next major version. The number of issues caused by needing to maintain two parallel resources made it a high priority for me to make this change.

**Pull request merged**
