### PR TITLE
Updated the Nexus3 OCI image to v3.55.0

### PR DESCRIPTION
**Pull request by SamuelBagattin**
Hi ! 
Quick PR to update nexus3 to latest version.

### CODE REVIEW

**Comment by stevehipwell** [comment]
@SamuelBagattin I don't see the GH release or release notes for this?

**Comment by SamuelBagattin** [comment]
Here are the Nexus release notes : https://help.sonatype.com/repomanager3/product-information/release-notes/2023-release-notes/sonatype-nexus-repository-3.55.0-release-notes
And the github commit that initiated the new version : https://github.com/sonatype/docker-nexus3/commit/f99851b30556a277eae9834576122638f59a0222

**Comment by stevehipwell** [comment]
@SamuelBagattin could you rebase and then update the chart version, chart annotations and CHANGELOG in line with previous releases.

**Comment by SamuelBagattin** [comment]
I just updated the changelog, but the GH release has not been created.
For the chart, i already updated its version, and I don't find any annotations to edit.

**Comment by SamuelBagattin** [comment]
Edit : The release has just been created https://github.com/sonatype/nexus-public/releases/tag/release-3.55.0-01

**Pull request merged**
