### PR TITLE
Upstream fixes

### PR DESCRIPTION
**Pull request by Jasper-Ben**
work in progress, more might follow.

### CODE REVIEW

**Comment by stevehipwell** [comment]
Thanks @Jasper-Ben I'm just testing some config changes and found the same issue that you've documented here. It looks like older versions of K8s didn't error with this. I'll fix it on my branch but leave this PR open for if you find anything else.

**Comment by stevehipwell** [comment]
@Jasper-Ben try [v2.5.1](https://github.com/stevehipwell/helm-charts/releases/tag/nexus3-2.5.1) of the chart a sit should fix your issues.

**Comment by Jasper-Ben** [comment]
@stevehipwell thanks for your work! seems like I just added some more duplicated work on top... bad timing :laughing: Will try your new release and report back if I find any issues. With my current fork I still run into issues when trying to add groovy scripts due to https://issues.sonatype.org/browse/NEXUS-23205. Setting parameters.enabled and parameters.values accordingly caused the nexus bootstrapping to fail due to permission errors (writing to $nexus_dir/etc/foo. I presume this happens since the parameters are mounted readOnly to $nexus_path/etc/nexus.parameters, creating the /etc/ folder in progress, which might not have to proper permissions set. I tried creating the etc folder in the bootstrap phase as a fix, but was not yet able to verify. But maybe this does not occur in your new version... so just something to be aware of :+1:

**Comment by stevehipwell** [comment]
@Jasper-Ben the latest release should fix your issues as I ran it through CI with those settings. Although I've just realised that the config parameters are a breaking change, but they are now documented in the readme.

**Comment by Jasper-Ben** [comment]
just some stuff I noticed on a first glance:

documentation says there is no cleanup etc. enabled by default:

config.cleanup | Nexus3 cleanup policies to be configured. | []
-- | -- | --
config.repos | Nexus3 repos to be configured. | []
config.tasks | Nexus3 tasks to be configured. | []

However there are already predefined configs enabled in values.yaml

**Comment by Jasper-Ben** [comment]
as far as I can tell the script issue still persists. I will create a separate issue to keep things a bit tidier

**Comment by Jasper-Ben** [comment]
superseded by https://github.com/stevehipwell/helm-charts/pull/56

**Pull request closed without merging**
