### PR TITLE
[confluence-server] Fix port formatting issue for  jdbc url

### LINKED ISSUE #457: [confluence-server] ATL_JDBC_URL port formats incorrectly
Using `v4.8.2` our helm terraform diff shows odd formatting around the port:

```text
~ value = "jdbc:postgresql://<host>:5432/confluence" -> "jdbc:postgresql://<host>:%!s(float64=5432)/confluence"
```

### PR DESCRIPTION
**Pull request by mcwarman**
Fixes #457

No rush needed, can wait till you're not AFK.

Also added helm [unittest](https://github.com/quintush/helm-unittest).

### CODE REVIEW

**Comment by mcwarman** [comment]
This does also work:

```
value: {{ printf "jdbc:postgresql://%v:%v/%v" .Values.psql.host (default 5432 .Values.psql.port) .Values.psql.database | quote }}
```

**Comment by stevehipwell** [comment]
@mcwarman could you switch your implementation to use `%v` as that's what's used in other charts and what I've got sitting locally (I was waiting for the next patch release but I think I just updated the image when it happened and forgot about this).

Do the unit test files need to use a `_` or can they use `-`?

Could you also update `_release-notes.md`?

**Comment by mcwarman** [comment]
@stevehipwell Sorry for the delay on the changes, I see you've made a merge #467 with a new release, did you want me to merge the changes in to this branch?

**Comment by stevehipwell** [comment]
@mcwarman if you rebase I'll get your changes merged in.

**Comment by stevehipwell** [comment]
@mcwarman I've released the latest Confluence version to fix the major CVE and if you rebase this PR I'll get this merged for you on top of it.

**Pull request closed without merging**
