### PR TITLE
Thanos: Parameterize default kubernetes cluster domain

### PR DESCRIPTION
**Pull request by BigYopy**
When the default clusterdomain is not `cluster.local` query fails to find thanos stores

### CODE REVIEW

**Review by stevehipwell — CHANGES_REQUESTED** [review]
Thanks @BigYopy. Could you also add an entry to the CHANGELOG under the `[UNRELEASED]` section?

**Comment by BigYopy** [comment]
> Thanks @BigYopy. Could you also add an entry to the CHANGELOG under the `[UNRELEASED]` section?

@stevehipwell done ✅

**Review by stevehipwell — CHANGES_REQUESTED** [review]
Sorry @BigYopy I missed that you also hadn't updated the README. Could you add the new value in?

**Comment by BigYopy** [comment]
> Sorry @BigYopy I missed that you also hadn't updated the README. Could you add the new value in?

done ✅

**Review by stevehipwell — APPROVED** [review]
LGTM

**Pull request merged**
