### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jasper-Ben**

### CODE REVIEW

**Comment by stevehipwell** [comment]
@Jasper-Ben you haven't added a description as to why you've made this PR so I'm not sure why you've made it but the change suggested would be incorrect as the README.md and values.yaml match correctly.

**Comment by Jasper-Ben** [comment]
Hi @stevehipwell, sorry for the lack of input. I assumed it was a simple, obvious typo in the readme (and didn't bother to check the values.yml - silly me).

However, for some reason (and I did not overwrite the default service.port value :wink:) the service got exposed on 8081. I am using template version 2.4.0 from your helm repo. Any idea why this might be the case? :thinking:

**Comment by stevehipwell** [comment]
@Jasper-Ben the deployment/pod container port doesn't match the service port as it's hard coded. I'll take a look on my cluster tomorrow and align this with my other charts as it's looking a bit tired!

**Comment by Jasper-Ben** [comment]
> @Jasper-Ben the deployment/pod container port doesn't match the service port as it's hard coded. I'll take a look on my cluster tomorrow and align this with my other charts as it's looking a bit tired!

Yes, just realised that myself... thanks! :smile:

**Pull request closed without merging**
