### PR TITLE
fix volume(mount) template

### PR DESCRIPTION
**Pull request by Jasper-Ben**

### CODE REVIEW

**Comment by stevehipwell** [comment]
I did wonder about the `tpl` bit. I'll merge in a bit.

**Comment by Jasper-Ben** [comment]
give me sec, I'm still testing the blobStore part

**Comment by Jasper-Ben** [comment]
OK, so the blobStore part still fails... will have to look into this first

**Comment by Jasper-Ben** [comment]
This should do the trick.

**Comment by stevehipwell** [comment]
@Jasper-Ben ready for a merge?

**Comment by Jasper-Ben** [comment]
> @Jasper-Ben ready for a merge?

Not yet unfortunately. I just noticed that s3 and file typed creations respond with different success codes. The current setup will fail for s3 storage. I will fix this tomorrow.

**Comment by stevehipwell** [comment]
>Not yet unfortunately. I just noticed that s3 and file typed creations respond with different success codes. The current setup will fail for s3 storage. I will fix this tomorrow.

I'd suggest opening a ticket on the [Nexus Jira](https://issues.sonatype.org/projects/NEXUS/issues/NEXUS-24416?filter=allopenissues) if the behaviour is unexpected.

**Comment by Jasper-Ben** [comment]
> > Not yet unfortunately. I just noticed that s3 and file typed creations respond with different success codes. The current setup will fail for s3 storage. I will fix this tomorrow.
> 
> I'd suggest opening a ticket on the [Nexus Jira](https://issues.sonatype.org/projects/NEXUS/issues/NEXUS-24416?filter=allopenissues) if the behaviour is unexpected.

Not really an issue, as both 204 and 201 are valid response codes for a successful API requests.

**Comment by Jasper-Ben** [comment]
Can be merged :+1:

**Pull request merged**
