### PR TITLE
feat[vertical-pod-autoscaler]: Add chart

### PR DESCRIPTION
**Pull request by stevehipwell**

### CODE REVIEW

**Comment by bukowa** [comment]
Hey! Is the test failing with exit code 128 because there is no chart to compare with ct diff tool ?

**Comment by stevehipwell** [comment]
@bukowa this PR is draft as I've not finished it. I will be getting it working soon but until it's no longer flagged as draft it wont work.

**Comment by bukowa** [comment]
Thanks for reply. Sorry i should have stated in the first post what i mean exactly. I can see that github action test `Lint and Test Charts` is failing but i cannot see the output because it was a long time ago when it ran. 

I myself created a pull request in my own `charts` repository where i got the same test failing because there was no chart to compare (like in your case charts/vertical-pod-autoscaler does not exist). I wonder if that's the same case here! See https://github.com/bukowa/charts/pull/2

**Pull request merged**
